# Generated by Django 5.2.17 on 2026-09-13 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('high_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_high_pairs', to=settings.AUTH_USER_MODEL)),
                ('low_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_low_pairs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friendship', to='social.relationshippair')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_blocks_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-blocked_at', 'id'),
                'indexes': [models.Index(fields=['blocker', 'is_active'], name='social_blocker_active'), models.Index(fields=['blocked', 'is_active'], name='social_blocked_active')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='social_unique_block_direction'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='social_block_no_self')],
            },
        ),
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendship_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendship_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
                'indexes': [models.Index(fields=['sender', 'status'], name='social_request_sender_status'), models.Index(fields=['receiver', 'status'], name='social_request_receiver_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='social_request_no_self'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'rejected', 'blocked'])), name='social_request_status_valid'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender', 'receiver'), name='social_unique_pending_request_direction')],
            },
        ),
        migrations.AddIndex(
            model_name='relationshippair',
            index=models.Index(fields=['low_user', 'high_user'], name='social_pair_lookup'),
        ),
        migrations.AddConstraint(
            model_name='relationshippair',
            constraint=models.UniqueConstraint(fields=('low_user', 'high_user'), name='social_unique_relationship_pair'),
        ),
        migrations.AddConstraint(
            model_name='relationshippair',
            constraint=models.CheckConstraint(condition=models.Q(('low_user__lt', models.F('high_user'))), name='social_pair_users_canonical'),
        ),
    ]
