# Generated by Django 5.2.17 on 2026-09-13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalogue", "0019_phase6_catalogue_publishers"),
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("message", models.CharField(blank=True, default="", max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("hidden_reason", models.CharField(blank=True, default="", max_length=24)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_messages_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_recommendations",
                        to="catalogue.gamework",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "indexes": [
                    models.Index(fields=("receiver", "read_at"), name="social_message_unread"),
                    models.Index(fields=("sender", "receiver", "created_at"), name="social_msg_cooldown_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="socialmessage",
            constraint=models.CheckConstraint(
                condition=~models.Q(sender=models.F("receiver")), name="social_message_no_self"
            ),
        ),
        migrations.AddConstraint(
            model_name="socialmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("hidden_at__isnull", True), ("hidden_reason", ""))
                | models.Q(("hidden_at__isnull", False)),
                name="social_message_hidden_reason_consistent",
            ),
        ),
    ]
