# Generated by Django 5.2.17 on 2026-10-04 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_phase6_catalogue_publishers'),
        ('social', '0002_socialmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmessage',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmessage',
            name='response',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.CreateModel(
            name='SocialNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('accepted', 'Friend request accepted'), ('rec_added', 'Recommendation added to backlog')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_notices_caused', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_notices', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_notices', to='catalogue.gamework')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='social_notice_unread')],
                'constraints': [models.CheckConstraint(condition=models.Q(('recipient', models.F('actor')), _negated=True), name='social_notice_no_self'), models.CheckConstraint(condition=models.Q(('kind__in', ['accepted', 'rec_added'])), name='social_notice_kind_valid')],
            },
        ),
    ]
