from django.urls import path

from social.views import (
    AcceptFriendshipRequestView,
    BlockUserView,
    FriendCardView,
    FriendProfileView,
    FriendshipActionView,
    FriendshipCollectionView,
    FriendshipRequestActionView,
    FriendshipRequestCollectionView,
    NotificationCollectionView,
    NotificationReadAllView,
    RecommendationRespondView,
    RelationshipView,
    RejectFriendshipRequestView,
    RemoveFriendshipView,
    RecommendationCollectionView,
    SocialSearchView,
    SocialMessageCollectionView,
    SocialMessageReadView,
    SocialMessageUnreadCountView,
    SocialMessageUnreadView,
    UnblockUserView,
)

app_name = "social"

urlpatterns = [
    path("search/", SocialSearchView.as_view(), name="search"),
    path("recommendations/", RecommendationCollectionView.as_view(), name="recommendations"),
    path("messages/", SocialMessageCollectionView.as_view(), name="messages"),
    path("messages/unread-count/", SocialMessageUnreadCountView.as_view(), name="messages-unread-count"),
    path("notifications/", NotificationCollectionView.as_view(), name="notifications"),
    path("notifications/read-all/", NotificationReadAllView.as_view(), name="notifications-read-all"),
    path("friends/<str:alias>/", FriendCardView.as_view(), name="friend-card"),
    path("friends/<str:alias>/profile/", FriendProfileView.as_view(), name="friend-profile"),
    path("messages/<uuid:message_id>/respond/", RecommendationRespondView.as_view(), name="message-respond"),
    path("messages/<uuid:message_id>/read/", SocialMessageReadView.as_view(), name="message-read"),
    path("messages/<uuid:message_id>/unread/", SocialMessageUnreadView.as_view(), name="message-unread"),
    path("requests/", FriendshipRequestCollectionView.as_view(), name="requests"),
    path("requests/<uuid:request_id>/accept/", AcceptFriendshipRequestView.as_view(), name="request-accept"),
    path("requests/<uuid:request_id>/reject/", RejectFriendshipRequestView.as_view(), name="request-reject"),
    path("requests/<uuid:request_id>/<str:action>/", FriendshipRequestActionView.as_view(), name="request-action"),
    path("friendships/", FriendshipCollectionView.as_view(), name="friendships"),
    path("friendships/<str:alias>/remove/", RemoveFriendshipView.as_view(), name="friendship-remove"),
    path("friendships/<str:alias>/block/", BlockUserView.as_view(), name="friendship-block"),
    path("relationships/<str:alias>/", RelationshipView.as_view(), name="relationship"),
    path("blocks/<str:alias>/unblock/", UnblockUserView.as_view(), name="unblock"),
    path("relationships/<str:alias>/<str:action>/", FriendshipActionView.as_view(), name="relationship-action"),
]
