"""Spanish names for the genre/tag vocabulary, keyed by slug.

Mirror of ``apps/web/lib/genre-labels.ts`` (the web interface translates the same
slugs); used by the spreadsheet export so the "Género" column reads like the
Spanish interface. A slug without an entry falls back to the original name."""

GENRE_LABELS_ES: dict[str, str] = {
    "action": "Acción",
    "adventure": "Aventura",
    "anime": "Anime",
    "arcade": "Arcade",
    "battle-royale": "Battle royale",
    "card-game": "Juego de cartas",
    "casual": "Casual",
    "comedy": "Comedia",
    "co-op": "Cooperativo",
    "cyberpunk": "Ciberpunk",
    "deckbuilder": "Construcción de mazos",
    "educational": "Educativo",
    "family-friendly": "Apto para familias",
    "fantasy": "Fantasía",
    "fighting": "Lucha",
    "hack-and-slash": "Hack and slash",
    "historical": "Histórico",
    "horror": "Terror",
    "indie": "Indie",
    "jrpg": "JRPG",
    "kids": "Infantil",
    "metroidvania": "Metroidvania",
    "mmo": "MMO",
    "moba": "MOBA",
    "multiplayer": "Multijugador",
    "music": "Música",
    "mystery": "Misterio",
    "open-world": "Mundo abierto",
    "party": "Fiesta",
    "pinball": "Pinball",
    "pixel-art": "Pixel art",
    "platformer": "Plataformas",
    "point-and-click": "Point-and-click",
    "puzzle": "Puzles",
    "racing": "Carreras",
    "retro": "Retro",
    "roguelike": "Roguelike",
    "romance": "Romance",
    "rpg": "RPG",
    "sandbox": "Sandbox",
    "sci-fi": "Ciencia ficción",
    "shooter": "Disparos",
    "side-scroller": "Scroll lateral",
    "simulation": "Simulación",
    "singleplayer": "Un jugador",
    "souls-like": "Souls-like",
    "split-screen": "Pantalla dividida",
    "sports": "Deportes",
    "stealth": "Sigilo",
    "story-rich": "Narrativa profunda",
    "strategy": "Estrategia",
    "superhero": "Superhéroes",
    "survival": "Supervivencia",
    "tactical": "Táctico",
    "trivia": "Preguntas y respuestas",
    "turn-based": "Por turnos",
    "visual-novel": "Novela visual",
    "vr": "Realidad virtual",
    "card-board-game": "Cartas y juegos de mesa",
    "hack-and-slashbeat-em-up": "Hack and slash / Beat 'em up",
    "platform": "Plataformas",
    "quiztrivia": "Preguntas y respuestas",
    "real-time-strategy-rts": "Estrategia en tiempo real (RTS)",
    "role-playing-rpg": "Rol (RPG)",
    "simulator": "Simulador",
    "sport": "Deportes",
    "turn-based-strategy-tbs": "Estrategia por turnos (TBS)",
}
