# Generated by Django 5.2.17 on 2026-09-05 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAccountIdentity',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('seed_key', models.CharField(max_length=64, unique=True)),
                ('is_simulated', models.BooleanField(default=True)),
                ('marker', models.CharField(default='simulated-demo-account', max_length=64)),
                ('display_label', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('seed_key',),
                'constraints': [models.CheckConstraint(condition=models.Q(('is_simulated', True)), name='accounts_demo_identity_always_simulated')],
            },
        ),
    ]
