# Generated by Django 5.2.17 on 2026-09-12 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_demo_accounts'),
        ('catalogue', '0018_merge_new_releases_and_curated_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, default='', max_length=500)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('collection_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=8)),
                ('favorites_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('collection_visibility__in', ['public', 'private'])), name='accounts_profile_collection_visibility_valid'), models.CheckConstraint(condition=models.Q(('favorites_visibility__in', ['public', 'private'])), name='accounts_profile_favorites_visibility_valid')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_slots', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favorited_by', to='catalogue.gamework')),
            ],
            options={
                'ordering': ('slot',),
                'constraints': [models.UniqueConstraint(fields=('user', 'slot'), name='accounts_favorite_unique_user_slot'), models.UniqueConstraint(fields=('user', 'work'), name='accounts_favorite_unique_user_work'), models.CheckConstraint(condition=models.Q(('slot__gte', 1), ('slot__lte', 5)), name='accounts_favorite_slot_range')],
            },
        ),
    ]
