# Generated by Django 5.2.17 on 2026-10-04 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phase7_anonymization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='avatar_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='avatar_image_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='avatar_preset',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='cover_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='cover_image_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='default_list_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=8),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='accountprofile',
            constraint=models.CheckConstraint(condition=models.Q(('default_list_visibility__in', ['public', 'private'])), name='accounts_profile_default_list_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='accountprofile',
            constraint=models.CheckConstraint(condition=models.Q(('avatar_preset__isnull', True), ('avatar_preset__lt', 5), _connector='OR'), name='accounts_profile_avatar_preset_valid'),
        ),
    ]
