# Generated by Django 5.2.17 on 2026-10-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_page_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
