# Generated by Django 5.2.17 (Plan 02-10 Task 3). Renamed from 0001_initial to
# 0001_work_feature_vector to name the change it makes.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0007_igdb_rating_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFeatureVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_set_version', models.CharField(max_length=64)),
                ('vector_json', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_vectors', to='catalogue.gamework')),
            ],
            options={
                'ordering': ('work_id', 'feature_set_version'),
                'constraints': [models.UniqueConstraint(fields=('work', 'feature_set_version'), name='recommendations_unique_work_feature_set')],
            },
        ),
    ]
