# Generated by Django 5.2.17 on 2026-09-09.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_work_feature_vector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("collection_revision", models.PositiveBigIntegerField()),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("corpus_version", models.CharField(blank=True, max_length=64, null=True)),
                ("feature_set_version", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("generated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recommendation_snapshots", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "collection_revision", "input_fingerprint"),
                        name="recommendations_unique_snapshot_revision",
                    ),
                ],
                "indexes": [models.Index(fields=["user", "-created_at"], name="recommendat_user_id_b0a957_idx")],
            },
        ),
        migrations.CreateModel(
            name="RecommendationState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("collection_revision", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_snapshot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="active_for_states", to="recommendations.recommendationsnapshot")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="recommendation_state", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="RecommendationRefreshJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("requested_revision", models.PositiveBigIntegerField()),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("obsolete", "Obsolete")], default="queued", max_length=16)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField()),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recommendation_refresh_jobs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("available_at", "created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "requested_revision"),
                        name="recommendations_unique_refresh_revision",
                    ),
                ],
                "indexes": [models.Index(fields=["status", "available_at"], name="recommendat_status_fd07d0_idx")],
            },
        ),
    ]
