# Generated by Django 5.2.17 on 2026-09-09.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_personalized_recommendation_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationrefreshjob",
            name="algorithm_id",
            field=models.CharField(default="legacy-bundle-v1", max_length=64),
        ),
        migrations.AddField(
            model_name="recommendationrefreshjob",
            name="configuration_fingerprint",
            field=models.CharField(default="legacy-v1", max_length=64),
        ),
        migrations.AddField(
            model_name="recommendationrefreshjob",
            name="result_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recommendationsnapshot",
            name="configuration_fingerprint",
            field=models.CharField(default="legacy-v1", max_length=64),
        ),
        migrations.RemoveConstraint(
            model_name="recommendationrefreshjob",
            name="recommendations_unique_refresh_revision",
        ),
        migrations.RemoveConstraint(
            model_name="recommendationsnapshot",
            name="recommendations_unique_snapshot_revision",
        ),
        migrations.AddConstraint(
            model_name="recommendationrefreshjob",
            constraint=models.UniqueConstraint(
                fields=("user", "requested_revision", "configuration_fingerprint", "algorithm_id"),
                name="recommendations_unique_refresh_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationsnapshot",
            constraint=models.UniqueConstraint(
                fields=("user", "collection_revision", "input_fingerprint", "configuration_fingerprint"),
                name="recommendations_unique_snapshot_revision",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationrefreshjob",
            index=models.Index(
                fields=["algorithm_id", "status", "available_at"],
                name="recommendat_algorit_d0ff28_idx",
            ),
        ),
    ]
