# Generated by Django 5.2.17 on 2026-09-11 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_parallel_recommendation_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSignalCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_revision', models.PositiveBigIntegerField()),
                ('configuration_fingerprint', models.CharField(max_length=64)),
                ('corpus_version', models.CharField(blank=True, max_length=64, null=True)),
                ('profile_inputs_json', models.JSONField()),
                ('rating_term_json', models.JSONField()),
                ('similarity_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_signal_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'requested_revision', 'configuration_fingerprint'), name='recommendations_unique_signal_cache')],
            },
        ),
    ]
