# Generated by Django 5.2.17 on 2026-09-04 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_slug', models.SlugField(max_length=200, unique=True)),
                ('original_title', models.CharField(max_length=300)),
                ('is_dlc', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('original_title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GameRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('release_name', models.CharField(max_length=300)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='catalogue.gamework')),
            ],
            options={
                'ordering': ('release_date', 'release_name', 'id'),
                'constraints': [models.UniqueConstraint(fields=('work', 'release_name'), name='catalogue_unique_release_name_per_work')],
            },
        ),
    ]
