# Generated by Django 5.2.17 on 2026-09-04 16:47

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        # pg_trgm powers the trigram-similarity fallback in tolerant search
        # (D-10/D-12, Pattern 5): exact/prefix match first, then trigram
        # similarity for small typos, over normalized aliases. Django's
        # makemigrations does not auto-detect this from GinIndex(opclasses=
        # ["gin_trgm_ops"]) alone -- the extension must be requested explicitly.
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='gamework',
            name='title_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='gamework',
            name='title_es',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='AssetAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('creator', models.CharField(blank=True, max_length=300)),
                ('licence', models.CharField(blank=True, max_length=150)),
                ('licence_url', models.URLField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('display_allowed', models.BooleanField(default=False)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='catalogue.gamework')),
            ],
            options={
                'ordering': ('work_id', 'id'),
            },
        ),
        migrations.AddField(
            model_name='gamerelease',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='catalogue.platform'),
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='catalogue.gamerelease')),
            ],
            options={
                'ordering': ('name', 'id'),
                'constraints': [models.UniqueConstraint(fields=('release', 'name'), name='catalogue_unique_edition_name_per_release')],
            },
        ),
        migrations.CreateModel(
            name='GameAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locale', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=2)),
                ('value', models.CharField(max_length=300)),
                ('normalized_value', models.CharField(db_index=True, max_length=300)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalogue.gamework')),
            ],
            options={
                'ordering': ('work_id', 'locale', 'value'),
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['normalized_value'], name='catalogue_alias_trgm_gin', opclasses=['gin_trgm_ops'])],
                'constraints': [models.UniqueConstraint(fields=('work', 'locale', 'normalized_value'), name='catalogue_unique_alias_per_work_locale')],
            },
        ),
        migrations.CreateModel(
            name='RelatedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('dlc', 'DLC'), ('expansion', 'Expansion')], max_length=16)),
                ('child_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_parents', to='catalogue.gamework')),
                ('parent_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_children', to='catalogue.gamework')),
            ],
            options={
                'ordering': ('parent_work_id', 'child_work_id'),
                'constraints': [models.UniqueConstraint(fields=('parent_work', 'child_work'), name='catalogue_unique_related_content_pair'), models.CheckConstraint(condition=models.Q(('parent_work', models.F('child_work')), _negated=True), name='catalogue_related_content_no_self_reference')],
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=50)),
                ('source_url', models.URLField(max_length=500)),
                ('retrieved_at', models.DateTimeField()),
                ('licence', models.CharField(max_length=100)),
                ('snapshot_sha256', models.CharField(max_length=64)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='catalogue.gamework')),
            ],
            options={
                'ordering': ('work_id', 'source'),
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='catalogue_unique_source_identity')],
            },
        ),
    ]
