# Generated by Django 5.2.17 on 2026-09-05 15:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_catalogue_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('igdb_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='gamework',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='works', to='catalogue.genre'),
        ),
        migrations.CreateModel(
            name='IgdbImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='igdb', max_length=50)),
                ('query_identity', models.CharField(max_length=200)),
                ('last_committed_igdb_id', models.BigIntegerField(default=0)),
                ('batches_committed', models.PositiveIntegerField(default=0)),
                ('works_imported', models.PositiveIntegerField(default=0)),
                ('works_updated', models.PositiveIntegerField(default=0)),
                ('genres_seen', models.PositiveIntegerField(default=0)),
                ('covers_present', models.PositiveIntegerField(default=0)),
                ('covers_fallback', models.PositiveIntegerField(default=0)),
                ('eligible_count_live', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('interrupted', 'Interrupted'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=16)),
                ('error_summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-started_at',),
                'constraints': [models.UniqueConstraint(fields=('source', 'query_identity'), name='catalogue_unique_igdb_import_identity'), models.CheckConstraint(condition=models.Q(('last_committed_igdb_id__gte', 0)), name='catalogue_igdb_cursor_non_negative')],
            },
        ),
        # Restart safety enforced at the database level: the id-cursor of a
        # resumable IGDB import must never regress. A BEFORE UPDATE trigger
        # rejects any statement (ORM save, bulk update, or raw SQL) that would
        # move last_committed_igdb_id to a lower value than the row already
        # holds, so a stale resume or a buggy caller cannot silently re-import
        # or skip a committed range.
        migrations.RunSQL(
            sql=(
                "CREATE FUNCTION catalogue_igdb_run_forward_only() RETURNS trigger AS $$\n"
                "BEGIN\n"
                "    IF NEW.last_committed_igdb_id < OLD.last_committed_igdb_id THEN\n"
                "        RAISE EXCEPTION 'IgdbImportRun.last_committed_igdb_id must not move backwards (% -> %)',\n"
                "            OLD.last_committed_igdb_id, NEW.last_committed_igdb_id\n"
                "            USING ERRCODE = 'check_violation';\n"
                "    END IF;\n"
                "    RETURN NEW;\n"
                "END;\n"
                "$$ LANGUAGE plpgsql;\n"
                "CREATE TRIGGER catalogue_igdb_run_forward_only\n"
                "    BEFORE UPDATE ON catalogue_igdbimportrun\n"
                "    FOR EACH ROW EXECUTE FUNCTION catalogue_igdb_run_forward_only();"
            ),
            reverse_sql=(
                "DROP TRIGGER IF EXISTS catalogue_igdb_run_forward_only ON catalogue_igdbimportrun;\n"
                "DROP FUNCTION IF EXISTS catalogue_igdb_run_forward_only();"
            ),
        ),
    ]
