# Generated by Django 5.2.17 on 2026-09-06 09:21

from django.db import migrations, models


def backfill_pass_cursor(apps, schema_editor):
    """A run that was mid-flight when this migration landed should keep
    resuming from where it actually was: seed pass_cursor from the old
    high-water mark for any non-COMPLETE run. A COMPLETE run keeps the
    default 0, so its next invocation starts a fresh full pass."""
    IgdbImportRun = apps.get_model("catalogue", "IgdbImportRun")
    IgdbImportRun.objects.exclude(status="complete").update(
        pass_cursor=models.F("last_committed_igdb_id")
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_catalogue_filter_sort_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='igdbimportrun',
            name='pass_cursor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.RunPython(backfill_pass_cursor, noop_reverse),
    ]
