# Generated by Django 5.2.17 on 2026-09-07

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_igdbimportrun_pass_cursor"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamework",
            name="corpus_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="gamework",
            name="in_corpus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gamework",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="gamework",
            index=models.Index(
                fields=["in_corpus", "first_release_date"],
                name="catalogue_work_corpus_idx",
            ),
        ),
        migrations.CreateModel(
            name="CorpusRatingSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "corpus_version",
                    models.CharField(max_length=32),
                ),
                (
                    "source",
                    models.CharField(max_length=16),
                ),
                (
                    "rating",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "rating_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "retrieved_at",
                    models.DateTimeField(),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_snapshots",
                        to="catalogue.gamework",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("work", "corpus_version", "source"),
                        name="catalogue_unique_rating_snapshot",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CorpusVersion",
            fields=[
                (
                    "version",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                (
                    "ruleset_sha256",
                    models.CharField(max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                ("governed_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
