# Generated by Django 5.2.17 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_governed_corpus"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamework",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamework",
            name="rating_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamework",
            name="total_rating_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
