# Generated by Django 5.2.17 on 2026-09-09 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_allow_duplicate_facet_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusPopularityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corpus_version', models.CharField(max_length=32)),
                ('score', models.FloatField()),
                ('formula_version', models.CharField(max_length=64)),
                ('calculated_at', models.DateTimeField()),
                ('source_snapshot_sha256', models.CharField(max_length=64)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_scores', to='catalogue.gamework')),
            ],
            options={
                'indexes': [models.Index(fields=['corpus_version', 'score'], name='catalogue_pop_score_idx')],
                'constraints': [models.UniqueConstraint(fields=('work', 'corpus_version'), name='catalogue_unique_popularity_score')],
            },
        ),
    ]
