# Generated by Django 5.2.17 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0012_corpuspopularityscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpusratingsnapshot",
            name="total_rating_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
