# Generated by Django 5.2.17 on 2026-09-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_igdb_content_facets'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewReleasesSnapshot',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('work_ids', models.JSONField(default=list)),
                ('formula', models.CharField(default='recency-0.70-popscore-0.30-v1', max_length=64)),
                ('computed_at', models.DateTimeField()),
            ],
        ),
    ]
